version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceTrashInspectionPlugin"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/ServiceTrashInspectionPlugin.Integration.Test"
  schedule:
    interval: daily